-- =====================================================================
-- WebForge seed data (catalogue + assessments)
-- Run after schema.sql. Users are NOT seeded here because password hashes
-- must be generated by PHP's password_hash(); see backend/bin/setup.php.
--
-- Answer-key conventions (enforced by the quiz grader):
--   mcq | true_false | find_error : question_options.is_correct marks the answer
--   output                         : payload_json = {"accepted": ["..."]}
--                                    (compared trimmed, case-insensitive, whitespace-
--                                     collapsed, surrounding quotes stripped)
--   match                          : payload_json = {"left":[..], "right":[..],
--                                    "answer":[rightIndexForLeft0, ...]}
--                                    The API strips "answer" before sending.
-- =====================================================================
USE webforge;

-- ---------------------------------------------------------------------
-- Concepts  (lab_path = frontend route that teaches the concept)
-- ---------------------------------------------------------------------
INSERT INTO concepts (id, slug, title, category, lab_path) VALUES
 (1,  'html-structure',   'HTML Document Structure',   'html',    '/lab/web-playground'),
 (2,  'css-styling',      'CSS Selectors & Styling',   'css',     '/lab/web-playground'),
 (3,  'js-basics',        'JavaScript Fundamentals',   'js',      '/lab/js-playground'),
 (4,  'js-functions',     'Functions, Objects & Arrays','js',     '/lab/js-playground'),
 (5,  'dom-manipulation', 'DOM Manipulation',          'dom',     '/lab/dom-explorer'),
 (6,  'dom-events',       'DOM Events',                'dom',     '/lab/event-visualizer'),
 (7,  'form-validation',  'Form Validation',           'dom',     '/lab/form-lab'),
 (8,  'ajax-fetch',       'AJAX & the Fetch API',      'ajax',    '/lab/ajax-monitor'),
 (9,  'http-basics',      'HTTP Methods & Status Codes','ajax',   '/lab/ajax-monitor'),
 (10, 'canvas-api',       'Canvas API',                'html',    '/lab/canvas-studio'),
 (11, 'php-basics',       'PHP Fundamentals',          'php',     '/lab/server-lab'),
 (12, 'php-sessions',     'Sessions & Authentication', 'php',     '/lab/server-lab/sessions'),
 (13, 'php-files',        'Server File Handling',      'php',     '/lab/server-lab/files'),
 (14, 'sql-crud',         'SQL CRUD Operations',       'sql',     '/lab/database-lab'),
 (15, 'react-components', 'React Components',          'react',   '/lab/component-studio'),
 (16, 'react-jsx',        'JSX',                       'react',   '/lab/component-studio/jsx'),
 (17, 'react-props',      'Props & Data Flow',         'react',   '/lab/component-studio/props'),
 (18, 'react-state',      'State & Re-rendering',      'react',   '/lab/state-lab'),
 (19, 'react-effects',    'useEffect & Lifecycle',     'react',   '/lab/state-lab/hooks'),
 (20, 'react-routing',    'Client-side Routing',       'routing', '/lab/routing-visualizer');

-- ---------------------------------------------------------------------
-- Experiment catalogue (every trackable activity in the platform)
-- ---------------------------------------------------------------------
INSERT INTO experiments (slug, module, title, concept_id) VALUES
 ('web-playground-run',   'web-playground',     'Run a web page in the live preview',  1),
 ('js-variables',         'js-playground',      'Variables & scope',                   3),
 ('js-data-types',        'js-playground',      'Data types & typeof',                 3),
 ('js-operators',         'js-playground',      'Operators & coercion',                3),
 ('js-conditions',        'js-playground',      'Conditional statements',              3),
 ('js-loops',             'js-playground',      'Loops',                               3),
 ('js-functions',         'js-playground',      'Functions & closures',                4),
 ('js-objects',           'js-playground',      'Objects',                             4),
 ('js-arrays',            'js-playground',      'Arrays & array methods',              4),
 ('dom-inspect',          'dom-explorer',       'Inspect and mutate the DOM',          5),
 ('event-flow',           'event-visualizer',   'Trace an event through its handler',  6),
 ('form-validation',      'form-lab',           'Client vs server validation',         7),
 ('ajax-request',         'ajax-monitor',       'Send and inspect an async request',   8),
 ('http-status',          'ajax-monitor',       'Explore HTTP status codes',           9),
 ('canvas-drawing',       'canvas-studio',      'Draw with the Canvas API',           10),
 ('php-variables',        'server-lab',         'PHP variables & types',              11),
 ('php-operators',        'server-lab',         'PHP operators',                      11),
 ('php-conditions',       'server-lab',         'PHP conditions',                     11),
 ('php-loops',            'server-lab',         'PHP loops',                          11),
 ('php-arrays',           'server-lab',         'PHP arrays',                         11),
 ('php-strings',          'server-lab',         'PHP string functions',               11),
 ('php-functions',        'server-lab',         'PHP functions',                      11),
 ('php-form-processing',  'server-lab',         'Process a submitted form',           11),
 ('php-sessions',         'server-lab',         'Session lifecycle',                  12),
 ('php-file-handling',    'server-lab',         'Create, write, append and read files',13),
 ('db-insert',            'database-lab',       'INSERT a row',                       14),
 ('db-select',            'database-lab',       'SELECT rows',                        14),
 ('db-update',            'database-lab',       'UPDATE a row',                       14),
 ('db-delete',            'database-lab',       'DELETE a row',                       14),
 ('component-tree',       'component-studio',   'Explore a component tree',           15),
 ('jsx-render',           'component-studio',   'JSX to React element to UI',         16),
 ('props-flow',           'component-studio',   'Follow props from parent to child',  17),
 ('state-update',         'state-lab',          'Update state and observe re-render', 18),
 ('hooks-effect',         'state-lab',          'useEffect with dependencies/cleanup',19),
 ('route-navigation',     'routing-visualizer', 'Navigate between routes',            20),
 ('fullstack-trace',      'execution-trace',    'Full-stack form execution trace',     7);

-- ---------------------------------------------------------------------
-- Quizzes
-- ---------------------------------------------------------------------
INSERT INTO quizzes (id, slug, title, description, concept_id, difficulty) VALUES
 (1, 'html-css-fundamentals', 'HTML & CSS Fundamentals', 'Document structure, semantic elements, selectors and the box model.', 1, 'beginner'),
 (2, 'javascript-core',       'JavaScript Core',         'Types, operators, functions, arrays and objects.',                    3, 'beginner'),
 (3, 'dom-and-events',        'DOM & Events',            'Selecting and changing elements, event flow and form validation.',    5, 'intermediate'),
 (4, 'ajax-and-http',         'AJAX & HTTP',             'Asynchronous requests, fetch, methods and status codes.',             8, 'intermediate'),
 (5, 'php-and-mysql',         'PHP & MySQL',             'Server-side processing, sessions, files and SQL.',                   11, 'intermediate'),
 (6, 'react-fundamentals',    'React Fundamentals',      'Components, JSX, props, state, effects and routing.',               15, 'intermediate');

-- ---------------------------------------------------------------------
-- Quiz 1: HTML & CSS
-- ---------------------------------------------------------------------
INSERT INTO quiz_questions (id, quiz_id, position, type, prompt, code_snippet, explanation, concept_id, payload_json) VALUES
 (1, 1, 1, 'mcq', 'Which element should wrap the primary, unique content of a page?', NULL,
  '<main> represents the dominant content of the <body>. There should be only one visible <main> per page.', 1, NULL),
 (2, 1, 2, 'true_false', 'An id attribute value may be used on several elements in the same document.', NULL,
  'False. id values must be unique within a document; use classes to target several elements.', 1, NULL),
 (3, 1, 3, 'mcq', 'Which selector has the highest specificity?', NULL,
  'An id selector (#nav) beats class (.nav) and element (nav) selectors. Inline styles and !important override all of them.', 2, NULL),
 (4, 1, 4, 'output', 'With box-sizing: content-box, what is the total rendered width (in px) of this box? Answer with a number.',
  '.box {\n  width: 200px;\n  padding: 10px;\n  border: 5px solid;\n  margin: 20px;\n}',
  'content-box: width + left/right padding + left/right border = 200 + 20 + 10 = 230px. Margin is outside the box.', 2,
  '{"accepted":["230","230px"]}'),
 (5, 1, 5, 'find_error', 'Which line makes this HTML invalid?',
  '1  <ul>\n2    <li>Home</li>\n3    <p>About</p>\n4    <li>Contact</li>\n5  </ul>',
  'A <ul> may only contain <li> (and script-supporting) elements. The <p> on line 3 must be inside an <li>.', 1, NULL),
 (6, 1, 6, 'match', 'Match each CSS property to what it controls.', NULL,
  'display controls the layout model, position the positioning scheme, z-index the stacking order and opacity the transparency.', 2,
  '{"left":["display","position","z-index","opacity"],"right":["Transparency","Layout model","Stacking order","Positioning scheme"],"answer":[1,3,2,0]}');

INSERT INTO question_options (question_id, position, label, is_correct) VALUES
 (1,1,'<section>',0),(1,2,'<main>',1),(1,3,'<div id="content">',0),(1,4,'<article>',0),
 (2,1,'True',0),(2,2,'False',1),
 (3,1,'nav ul li',0),(3,2,'.nav .item',0),(3,3,'#nav',1),(3,4,'ul > li',0),
 (5,1,'Line 1',0),(5,2,'Line 2',0),(5,3,'Line 3',1),(5,4,'Line 5',0);

-- ---------------------------------------------------------------------
-- Quiz 2: JavaScript core
-- ---------------------------------------------------------------------
INSERT INTO quiz_questions (id, quiz_id, position, type, prompt, code_snippet, explanation, concept_id, payload_json) VALUES
 (7, 2, 1, 'output', 'What does this log?', 'console.log(typeof null);',
  'typeof null is "object", a long-standing quirk kept for backward compatibility.', 3, '{"accepted":["object"]}'),
 (8, 2, 2, 'output', 'What does this log?', 'console.log(1 + "2" + 3);',
  'Evaluation goes left to right: 1 + "2" produces the string "12", then "12" + 3 produces "123".', 3, '{"accepted":["123"]}'),
 (9, 2, 3, 'mcq', 'Which comparison is true?', NULL,
  '0 == "" is true because == coerces both values to the number 0. The strict versions compare types too.', 3, NULL),
 (10, 2, 4, 'find_error', 'Why does this code throw an error?',
  'const total = 10;\ntotal = total + 5;\nconsole.log(total);',
  'A const binding cannot be reassigned. Use let when the variable must change.', 3, NULL),
 (11, 2, 5, 'output', 'What does this log?', 'const nums = [1, 2, 3, 4];\nconsole.log(nums.filter(n => n % 2 === 0).map(n => n * 10));',
  'filter keeps [2, 4], then map multiplies each by 10, giving [20, 40].', 4, '{"accepted":["[20, 40]","[20,40]","20,40"]}'),
 (12, 2, 6, 'true_false', 'Arrow functions get their own `this` binding when called as object methods.', NULL,
  'False. Arrow functions capture `this` from the scope that encloses them. They never bind their own.', 4, NULL),
 (13, 2, 7, 'match', 'Match each array method to what it returns.', NULL,
  'map gives a new array of transformed items, filter a new array of matching items, find the first match (or undefined) and reduce a single accumulated value.', 4,
  '{"left":["map","filter","find","reduce"],"right":["First matching element","Single accumulated value","New array of transformed items","New array of matching items"],"answer":[2,3,0,1]}');

INSERT INTO question_options (question_id, position, label, is_correct) VALUES
 (9,1,'0 === ""',0),(9,2,'0 == ""',1),(9,3,'null === undefined',0),(9,4,'NaN == NaN',0),
 (10,1,'console.log cannot print numbers',0),(10,2,'A const variable cannot be reassigned',1),(10,3,'total is not defined',0),(10,4,'Missing semicolon on line 1',0),
 (12,1,'True',0),(12,2,'False',1);

-- ---------------------------------------------------------------------
-- Quiz 3: DOM & Events
-- ---------------------------------------------------------------------
INSERT INTO quiz_questions (id, quiz_id, position, type, prompt, code_snippet, explanation, concept_id, payload_json) VALUES
 (14, 3, 1, 'mcq', 'What does document.querySelector(".card") return when several elements match?', NULL,
  'querySelector returns the first matching element. querySelectorAll returns a static NodeList of every match.', 5, NULL),
 (15, 3, 2, 'mcq', 'Which property safely sets text without parsing HTML?', NULL,
  'textContent treats the value as plain text, which prevents HTML injection. innerHTML parses markup.', 5, NULL),
 (16, 3, 3, 'mcq', 'In which order do the phases of event propagation run?', NULL,
  'Events go through the capture phase (window down to target), then the target phase, then bubble back up.', 6, NULL),
 (17, 3, 4, 'find_error', 'The form reloads the page instead of validating. What is missing?',
  'form.addEventListener("submit", (e) => {\n  if (!email.value.includes("@")) {\n    showError("Invalid email");\n  }\n});',
  'Without e.preventDefault() the browser performs its default action, which submits the form and reloads the page.', 7, NULL),
 (18, 3, 5, 'true_false', 'Client-side validation alone is enough to protect a server from invalid data.', NULL,
  'False. Client-side checks improve UX but can be bypassed. The server must always validate again.', 7, NULL),
 (19, 3, 6, 'match', 'Match each event to when it fires.', NULL,
  'input fires on every value change, change when the value is committed, keydown when a key is pressed and submit when a form is submitted.', 6,
  '{"left":["input","change","keydown","submit"],"right":["A form is submitted","Every edit to a field value","A key is pressed","A value is committed (e.g. on blur)"],"answer":[1,3,2,0]}');

INSERT INTO question_options (question_id, position, label, is_correct) VALUES
 (14,1,'An array of all matches',0),(14,2,'The first matching element',1),(14,3,'The last matching element',0),(14,4,'null',0),
 (15,1,'innerHTML',0),(15,2,'outerHTML',0),(15,3,'textContent',1),(15,4,'insertAdjacentHTML',0),
 (16,1,'Bubble → Target → Capture',0),(16,2,'Target → Bubble → Capture',0),(16,3,'Capture → Target → Bubble',1),(16,4,'Capture → Bubble → Target',0),
 (17,1,'e.stopPropagation()',0),(17,2,'e.preventDefault()',1),(17,3,'return true',0),(17,4,'form.reset()',0),
 (18,1,'True',0),(18,2,'False',1);

-- ---------------------------------------------------------------------
-- Quiz 4: AJAX & HTTP
-- ---------------------------------------------------------------------
INSERT INTO quiz_questions (id, quiz_id, position, type, prompt, code_snippet, explanation, concept_id, payload_json) VALUES
 (20, 4, 1, 'mcq', 'Which HTTP method is idempotent and is normally used to replace a resource?', NULL,
  'PUT replaces the target resource; repeating the same PUT gives the same result. POST is not idempotent.', 9, NULL),
 (21, 4, 2, 'mcq', 'A request is sent without a valid session cookie to a protected endpoint. What status fits best?', NULL,
  '401 Unauthorized means authentication is missing or invalid. 403 means authenticated but not allowed.', 9, NULL),
 (22, 4, 3, 'true_false', 'fetch() rejects its promise when the server responds with HTTP 404.', NULL,
  'False. fetch only rejects on network failure. A 404 resolves normally with response.ok === false.', 8, NULL),
 (23, 4, 4, 'output', 'In what order are the letters logged? Answer like: A B C', 'console.log("A");\nsetTimeout(() => console.log("B"), 0);\nPromise.resolve().then(() => console.log("C"));\nconsole.log("D");',
  'Synchronous code runs first (A, D). Then the microtask queue runs (C), then the timer (macrotask) queue runs (B).', 8, '{"accepted":["A D C B","ADCB","A, D, C, B"]}'),
 (24, 4, 5, 'find_error', 'Why is `data` always undefined here?',
  'function loadUsers() {\n  let data;\n  fetch("/api/users").then(r => r.json()).then(j => { data = j; });\n  return data;\n}',
  'fetch is asynchronous. The function returns before the promise resolves. Make it async and await the result instead.', 8, NULL),
 (25, 4, 6, 'match', 'Match each status code to its meaning.', NULL,
  '200 OK, 201 Created, 422 Unprocessable Content (validation failed), 500 Internal Server Error.', 9,
  '{"left":["200","201","422","500"],"right":["Server error","Validation failed","Resource created","Success"],"answer":[3,2,1,0]}');

INSERT INTO question_options (question_id, position, label, is_correct) VALUES
 (20,1,'POST',0),(20,2,'PUT',1),(20,3,'PATCH',0),(20,4,'CONNECT',0),
 (21,1,'400',0),(21,2,'401',1),(21,3,'403',0),(21,4,'404',0),
 (22,1,'True',0),(22,2,'False',1),
 (24,1,'The URL is wrong',0),(24,2,'r.json() is synchronous',0),(24,3,'The function returns before the asynchronous request finishes',1),(24,4,'let cannot be reassigned',0);

-- ---------------------------------------------------------------------
-- Quiz 5: PHP & MySQL
-- ---------------------------------------------------------------------
INSERT INTO quiz_questions (id, quiz_id, position, type, prompt, code_snippet, explanation, concept_id, payload_json) VALUES
 (26, 5, 1, 'output', 'What does this PHP print?', '<?php\n$a = "5";\n$b = 3;\necho $a . $b;',
  'The . operator concatenates strings, so "5" . 3 gives "53". Arithmetic + would give 8.', 11, '{"accepted":["53"]}'),
 (27, 5, 2, 'mcq', 'Which approach prevents SQL injection?', NULL,
  'Prepared statements send the SQL and the data separately, so input is never interpreted as SQL.', 14, NULL),
 (28, 5, 3, 'mcq', 'How should passwords be stored?', NULL,
  'password_hash() uses a slow, salted algorithm (bcrypt/argon2). Verify with password_verify().', 12, NULL),
 (29, 5, 4, 'find_error', 'Which line is a security problem?',
  '1  $file = $_GET["name"];\n2  $path = __DIR__ . "/storage/" . $file;\n3  echo file_get_contents($path);',
  'Line 2 uses raw user input in a path, so "../" sequences can read any file (path traversal). Whitelist the name and check realpath().', 13, NULL),
 (30, 5, 5, 'true_false', 'session_regenerate_id(true) should be called after a successful login.', NULL,
  'True. A new session id after login prevents session fixation attacks.', 12, NULL),
 (31, 5, 6, 'match', 'Match each SQL statement to its CRUD operation.', NULL,
  'INSERT creates, SELECT reads, UPDATE changes and DELETE removes rows.', 14,
  '{"left":["INSERT","SELECT","UPDATE","DELETE"],"right":["Read","Delete","Create","Update"],"answer":[2,0,3,1]}'),
 (32, 5, 7, 'mcq', 'What does an UPDATE without a WHERE clause do?', NULL,
  'With no WHERE clause, every row in the table is updated. Always scope writes.', 14, NULL);

INSERT INTO question_options (question_id, position, label, is_correct) VALUES
 (27,1,'addslashes() on every input',0),(27,2,'Prepared statements with bound parameters',1),(27,3,'Using POST instead of GET',0),(27,4,'Hiding errors from users',0),
 (28,1,'md5($password)',0),(28,2,'base64_encode($password)',0),(28,3,'password_hash($password, PASSWORD_DEFAULT)',1),(28,4,'Encrypted with a key in config.php',0),
 (29,1,'Line 1',0),(29,2,'Line 2',1),(29,3,'Line 3',0),
 (30,1,'True',1),(30,2,'False',0),
 (32,1,'Fails with a syntax error',0),(32,2,'Updates only the first row',0),(32,3,'Updates every row in the table',1),(32,4,'Does nothing',0);

-- ---------------------------------------------------------------------
-- Quiz 6: React
-- ---------------------------------------------------------------------
INSERT INTO quiz_questions (id, quiz_id, position, type, prompt, code_snippet, explanation, concept_id, payload_json) VALUES
 (33, 6, 1, 'mcq', 'What does JSX compile to?', NULL,
  'JSX is syntax sugar for React.createElement(type, props, ...children) calls (or the jsx() runtime), which produce plain element objects.', 16, NULL),
 (34, 6, 2, 'true_false', 'A child component may modify the props it receives.', NULL,
  'False. Props are read-only. To change data, the child calls a callback passed down by the parent, which updates its own state.', 17, NULL),
 (35, 6, 3, 'output', 'The button is clicked once. What is displayed?',
  'function Counter() {\n  const [count, setCount] = useState(0);\n  const add = () => { setCount(count + 1); setCount(count + 1); };\n  return <button onClick={add}>{count}</button>;\n}',
  'Both calls read the same stale `count` (0) from this render, so the state becomes 1. Use setCount(c => c + 1) to apply both updates.', 18, '{"accepted":["1"]}'),
 (36, 6, 4, 'find_error', 'Why does this component loop forever?',
  'function Users() {\n  const [users, setUsers] = useState([]);\n  useEffect(() => {\n    fetch("/api/users").then(r => r.json()).then(setUsers);\n  });\n  return <List items={users} />;\n}',
  'The effect has no dependency array, so it runs after every render. Each setUsers causes another render. Add [] to run it once.', 19, NULL),
 (37, 6, 5, 'mcq', 'When does the cleanup function returned by useEffect run?', NULL,
  'Cleanup runs before the effect re-runs (when dependencies change) and when the component unmounts.', 19, NULL),
 (38, 6, 6, 'mcq', 'In React Router, which component renders the matched child route inside a layout?', NULL,
  '<Outlet /> is the placeholder where a parent route renders its matched child route.', 20, NULL),
 (39, 6, 7, 'match', 'Match each React concept to its description.', NULL,
  'Props are inputs from the parent, state is data owned by the component, key identifies list items and ref holds a mutable value that does not trigger re-render.', 15,
  '{"left":["props","state","key","ref"],"right":["Stable identity for list items","Mutable value that does not trigger a re-render","Read-only inputs from the parent","Data owned by the component that triggers re-render"],"answer":[2,3,0,1]}');

INSERT INTO question_options (question_id, position, label, is_correct) VALUES
 (33,1,'HTML strings',0),(33,2,'React.createElement calls',1),(33,3,'Direct DOM API calls',0),(33,4,'Web Components',0),
 (34,1,'True',0),(34,2,'False',1),
 (36,1,'useState must be called inside useEffect',0),(36,2,'The effect has no dependency array so it runs after every render',1),(36,3,'fetch cannot be used in components',0),(36,4,'List is not imported',0),
 (37,1,'Only when the component mounts',0),(37,2,'Before the effect re-runs and when the component unmounts',1),(37,3,'After every state change regardless of dependencies',0),(37,4,'Never, it must be called manually',0),
 (38,1,'<Route />',0),(38,2,'<Link />',0),(38,3,'<Outlet />',1),(38,4,'<Navigate />',0);
